<?xml version="1.0"?>
<definitions name="AuthenticationService"
            targetNamespace="urn:liberty:ssos:2006-08"
            xmlns:tns="urn:liberty:ssos:2006-08"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:S="http://schemas.xmlsoap.org/wsdl/soap/"
            xmlns="http://schemas.xmlsoap.org/wsdl/"
            xmlns:ssos="urn:liberty:ssos:2006-08"
            xmlns:samlp2="urn:oasis:names:tc:SAML:2.0:protocol"
            xmlns:wsaw="http://www.w3.org/2006/02/addressing/wsdl"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/
                                http://schemas.xmlsoap.org/wsdl/
                http://www.w3.org/2006/02/addressing/wsdl
                http://www.w3.org/2006/02/addressing/wsdl/ws-addr-wsdl.xsd">

    <xsd:documentation>
The source code in this WSDL file was excerpted verbatim from:

Liberty ID-WSF Liberty ID-WSF Authentication, Single Sign-On, and Identity Mapping Services Specification
Version 2.0-errata-v1.0
28 November, 2006

Copyright (c) 2007 Liberty Alliance participants, see
http://projectliberty.org/resource_center/specifications/liberty_alliance_id_wsf_2_0_specifications/idwsf_feb_copyrights

    </xsd:documentation>

    <types>
        <xs:schema>
            <xs:import namespace="urn:oasis:names:tc:SAML:2.0:protocol"
                       schemaLocation="saml-schema-protocol-2.0.xsd"/>
        </xs:schema>
    </types>

    <message name="SSOSoapRequest">
        <part name="parameters" element="samlp2:AuthnRequest"/>
    </message>
    <message name="SSOSoapResponse">
        <part name="parameters" element="samlp2:Response"/>
    </message>
    
    <portType name="SSOSPortType">
        <operation name="SingleSignOn">
            <input  message="ssos:SSOSoapRequest"
                wsaw:Action="urn:liberty:ssos:2006-08:AuthnRequest"/>
            <output message="ssos:SSOSoapResponse"
                wsaw:Action="urn:liberty:ssos:2006-08:Response"/>
        </operation>
    </portType>
    <binding name="SSOSSoapBinding" type="ssos:SSOSPortType">
        <S:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SingleSignOn">
            <input> 
                    <S:body use="literal"/>
            </input>
            <output>
                    <S:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SSOService">
        <port name="SSOSPortType" binding="ssos:SSOSSoapBinding">
            <S:address location="http://example.com/idmapping"/>
        </port>
    </service>
</definitions>
