//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.17 at 12:32:20 PM CST 
//

package org.picketlink.identity.federation.ws.addressing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ProblemActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProblemActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2005/08/addressing}Action" minOccurs="0"/>
 *         &lt;element name="SoapAction" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProblemActionType", propOrder =
{"action", "soapAction"})
public class ProblemActionType extends BaseAddressingType
{

   protected AttributedURIType action;

   protected String soapAction;

   /**
    * Gets the value of the action property.
    * 
    * @return
    *     possible object is
    *     {@link AttributedURIType }
    *     
    */
   public AttributedURIType getAction()
   {
      return action;
   }

   /**
    * Sets the value of the action property.
    * 
    * @param value
    *     allowed object is
    *     {@link AttributedURIType }
    *     
    */
   public void setAction(AttributedURIType value)
   {
      this.action = value;
   }

   /**
    * Gets the value of the soapAction property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getSoapAction()
   {
      return soapAction;
   }

   /**
    * Sets the value of the soapAction property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setSoapAction(String value)
   {
      this.soapAction = value;
   }
}